definitions:
  CreateSemesterRequest:
    properties:
      endDate:
        example: "2023-12-31T23:59:59Z"
        type: string
      membershipDiscountFee:
        example: 5
        minimum: 0
        type: integer
      membershipFee:
        example: 10
        minimum: 0
        type: integer
      meta:
        type: string
      name:
        example: Fall 2023
        type: string
      rebuyFee:
        example: 2
        minimum: 0
        type: integer
      startDate:
        example: "2023-09-01T00:00:00Z"
        type: string
      startingBudget:
        example: 100
        minimum: 0
        type: number
    required:
    - endDate
    - membershipDiscountFee
    - membershipFee
    - name
    - rebuyFee
    - startDate
    type: object
  ErrorResponse:
    properties:
      code:
        description: Code is the HTTP status code for the error.
        type: integer
      message:
        description: Message is a more descriptive error message.
        type: string
      type:
        description: Type is the name of the HTTP status code.
        type: string
    type: object
  Semester:
    properties:
      currentBudget:
        example: 100
        type: number
      endDate:
        example: "2023-12-31T23:59:59Z"
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      membershipDiscountFee:
        example: 5
        type: integer
      membershipFee:
        example: 10
        type: integer
      meta:
        type: string
      name:
        example: Fall 2023
        type: string
      rebuyFee:
        example: 2
        type: integer
      startDate:
        example: "2023-09-01T00:00:00Z"
        type: string
      startingBudget:
        example: 100
        type: number
    type: object
info:
  contact:
    email: uwaterloopoker@gmail.com
    name: UWPSC Development Team
  description: This is the API for the UWPSC website.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: UWPSC API
  version: "1.0"
paths:
  /health:
    get:
      description: Check the health of the API service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - Health
  /semesters:
    get:
      description: List all semesters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Semester'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: List Semesters
      tags:
      - Semesters
    post:
      consumes:
      - application/json
      description: Create a new semester
      parameters:
      - description: Semester data
        in: body
        name: semester
        required: true
        schema:
          $ref: '#/definitions/CreateSemesterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Semester'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Create Semester
      tags:
      - Semesters
  /semesters/{id}:
    get:
      description: Get a specific semester by ID
      parameters:
      - description: Semester ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Semester'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get Semester
      tags:
      - Semesters
swagger: "2.0"
