version: "3.9"
services:
  server:
    build:
      context: .
      target: build
    command: sh -c "go build -buildvcs=false -gcflags \"all=-N -l\" -o /tmp/server main.go && dlv exec --continue --accept-multiclient --headless --listen :4040 /tmp/server start"
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=development
      - PORT=5000
      - DATABASE_URL=postgres://docker:password@db:5432/uwpokerclub_development
      - TEST_DATABASE_URL=postgres://docker:password@db:5432/uwpokerclub_test
    networks:
      - services
    security_opt:
      - "seccomp:unconfined"

  db:
    image: postgres:13.7-alpine
    volumes:
      - ./scripts/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - DATABASES=uwpokerclub
      - DATABASE_ENVS=development,test
    ports:
      - 5432:5432
    networks:
      - services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
networks:
  services:
    name: uwpokerclub_services_network
    external: true
