name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: docker build .
      - name: Lint source code
        run: npm run lint
      - name: Run tests
        run: npm test
  e2e:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup docker environment
        run: docker network create uwpokerclub_services_network
      - name: Change to E2E folder
        run: cd e2e-tests
      - name: Install Typescript
        run: npm install @percy/cypress typescript
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e-tests
          build: docker compose build
          start: docker compose up -d
          wait-on: 'http://localhost:5173'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

